name: Build and Deploy to ACR

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Get version'
      id: 'get-version'
      run: | 
        echo '::set-output name=GIT_HASH::$(git rev-parse --short "$GITHUB_SHA")'
    
    - name: 'Build'
      env:
        LFA_DB_PASSWORD: ${{ secrets.LFA_DB_PASSWORD }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        GIT_HASH: ${{ steps.get-version.outputs.GIT_HASH }}
      run: docker-compose build
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az storage -h     
    
    # Runs a single command using the runners shell
    # - name: Send greeting
    #   run: echo "Hello ${{ github.event.inputs.name }}"
