name: Build and Deploy to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Get version'
      id: 'get-version'
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}    

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: adotfrankpublic.azurecr.io
        username: adotfrankpublic
        password: ${{ secrets.ACR_PASSWORD }}

    - name: 'Build with docker-compose and push to ACR'
      env:
        LFA_DB_PASSWORD: ${{ secrets.LFA_DB_PASSWORD }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        GIT_HASH: ${{ env.GITHUB_SHA_SHORT }}
      run: | 
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        sudo mkdir -p $DOCKER_CONFIG/cli-plugins
        sudo curl -SL https://github.com/docker/compose/releases/download/v2.30.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        docker-compose build
        docker tag lfa-front:$GITHUB_SHA_SHORT adotfrankpublic.azurecr.io/lfa/lfa-front:$GITHUB_SHA_SHORT
        docker tag lfa-back:$GITHUB_SHA_SHORT adotfrankpublic.azurecr.io/lfa/lfa-back:$GITHUB_SHA_SHORT
        docker push adotfrankpublic.azurecr.io/lfa/lfa-front:$GITHUB_SHA_SHORT
        docker push adotfrankpublic.azurecr.io/lfa/lfa-back:$GITHUB_SHA_SHORT
      
    # deploy container app with updated images
    # - name: 'Deploy container app with bicep with updated images'
    #   uses: azure/arm-deploy@v1
    #   with:
    #     subscriptionId: d56e652e-758d-480a-8f0d-47f230264b4c
    #     resourceGroupName: lfa-container-apps
    #     template: ./deploy/main.bicep
    #     parameters: gitHash=${{ env.GITHUB_SHA_SHORT }} deploymentType=prod
    #     scope: subscription
    #     region: eastus
    #     failOnStdErr: false
    - name: 'Deploy (using bicep-deploy)'
      uses: azure/bicep-deploy/@v1
      with: 
        type: deploymentStack
        operation: create
        name: LFA2-Stack
        location: eastus
        scope: subscription
        subscriptionId: d56e652e-758d-480a-8f0d-47f230264b4c
        template-file: ./deploy/main.bicep
        # parameters: gitHash=${{ env.GITHUB_SHA_SHORT }} deploymentType=prod
        parameters-file: ./deploy/main.bicepparam
        action-on-unmanage-resources: detach
        action-on-unmanage-resourcegroups: detach
        # action-on-unmanage-managementgroup: detach
        deny-settings-mode: denyWriteAndDelete
        description: 'Manages all resources for LFA2'

            
