name: Build and Deploy to ACR

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Get version'
      id: 'get-version'
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    
    - name: 'Build'
      env:
        LFA_DB_PASSWORD: ${{ secrets.LFA_DB_PASSWORD }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        GIT_HASH: ${{ env.GITHUB_SHA_SHORT }}
      run: docker-compose build
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az storage -h     
    
    # Runs a single command using the runners shell
    # - name: Send greeting
    #   run: echo "Hello ${{ github.event.inputs.name }}"
